### ISSUE TITLE
The specified resource name length is not within the permissible limits when running L1

### ISSUE THREAD

**Issue by enricked** [bernardmaltais/eslz-template#17]
Error: Failed to get existing workspaces: storage: service returned error: StatusCode=400, ErrorCode=OutOfRangeInput, ErrorMessage=The specified resource name length is not within the permissible limits.
RequestId:31e1a732-d01e-0026-12da-4ead15000000
Time:2020-06-30T12:35:49.0007036Z, RequestInitiated=Tue, 30 Jun 2020 12:35:48 GMT, RequestId=31e1a732-d01e-0026-12da-4ead15000000, API Version=2018-03-28, QueryParameterName=, QueryParameterValue=

Error on or near line 645; exiting with status 1

trying to figure out and i saw
userDefinedString        = "law${var.project}"    
law$ looks bad in 20-storage-account.tf file

**Comment by nephinj** [comment]
What name did you have for your project variable?

**Comment by bernardmaltais** [comment]
This is now resolved by enforcing a minimum of 3 chars for the env name.
