### ISSUE TITLE
Error: Error listing existing group owners from Azure AD Group

### ISSUE THREAD

**Issue by enricked** [bernardmaltais/eslz-template#3]
**Complaining about resources which didn't exist, but after verification in portal resources existed properly.** 

Error: Error listing existing group owners from Azure AD Group with ID "903d5ccd-1b91-4c09-83b5-ff10cc3e82b2": graphrbac.GroupsClient#ListOwners: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Request_ResourceNotFound","date":"2020-06-22T17:43:55","message":{"lang":"en","value":"Resource '903d5ccd-1b91-4c09-83b5-ff10cc3e82b2' does not exist or one of its queried reference-property objects are not present."},"requestId":"6ba2e719-38a4-4e6e-a680-0d909a96b1d6"}}]

  on 5-Subscription-AADGroups.tf line 11, in resource "azuread_group" "L1_Subscription_Readers":
  11: resource "azuread_group" "L1_Subscription_Readers" {

Error: Error listing existing group owners from Azure AD Group with ID "93e3a3ed-0843-4809-bbf9-e39e31593b0f": graphrbac.GroupsClient#ListOwners: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Request_ResourceNotFound","date":"2020-06-22T17:43:55","message":{"lang":"en","value":"Resource '93e3a3ed-0843-4809-bbf9-e39e31593b0f' does not exist or one of its queried reference-property objects are not present."},"requestId":"67c95bc9-ab7c-45cd-9080-094a44818760"}}]

  on 5-Subscription-AADGroups.tf line 16, in resource "azuread_group" "L2_Subscription_Owners":
  16: resource "azuread_group" "L2_Subscription_Owners" {

Error: Error listing existing group owners from Azure AD Group with ID "14d467f3-02eb-48f2-89cb-83366190b3b1": graphrbac.GroupsClient#ListOwners: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Request_ResourceNotFound","date":"2020-06-22T17:43:55","message":{"lang":"en","value":"Resource '14d467f3-02eb-48f2-89cb-83366190b3b1' does not exist or one of its queried reference-property objects are not present."},"requestId":"54a50ddd-5422-41dc-9637-979e3f02355b"}}]

  on 5-Subscription-AADGroups.tf line 26, in resource "azuread_group" "L2_Subscription_Readers":
  26: resource "azuread_group" "L2_Subscription_Readers" {

 **I run the script again and all run properly this time.**

azuread_group.L2_Subscription_Readers: Destroying... [id=14d467f3-02eb-48f2-89cb-83366190b3b1]
azuread_group.L1_Subscription_Readers: Destroying... [id=903d5ccd-1b91-4c09-83b5-ff10cc3e82b2]
azuread_group.L2_Subscription_Owners: Destroying... [id=93e3a3ed-0843-4809-bbf9-e39e31593b0f]
azuread_group.L2_Subscription_Owners: Destruction complete after 0s
azuread_group.L1_Subscription_Readers: Destruction complete after 0s
azuread_group.L2_Subscription_Owners: Creating...
azuread_group.L2_Subscription_Readers: Destruction complete after 0s
azuread_group.L1_Subscription_Readers: Creating...
azuread_group.L2_Subscription_Readers: Creating...
azuread_group.L2_Subscription_Owners: Still creating... [10s elapsed]
azuread_group.L1_Subscription_Readers: Still creating... [10s elapsed]
azuread_group.L2_Subscription_Readers: Still creating... [10s elapsed]
azuread_group.L2_Subscription_Owners: Creation complete after 10s [id=b5b6c76b-ce1a-4d42-b5e7-f92fab0be47b]
azurerm_role_assignment.L2_Subscription_Owners: Creating...
azuread_group.L2_Subscription_Readers: Creation complete after 11s [id=974839c4-9ac7-4e5a-a473-7a2c8547d2a8]
azurerm_role_assignment.L2_Subscription_Readers: Creating...
azuread_group.L1_Subscription_Readers: Creation complete after 11s [id=62266405-0692-4da4-9bee-b72b2aa23ac9]
azurerm_role_assignment.L1_Subscription_Readers: Creating...
azurerm_role_assignment.L2_Subscription_Owners: Still creating... [10s elapsed]
azurerm_role_assignment.L2_Subscription_Readers: Still creating... [10s elapsed]
azurerm_role_assignment.L1_Subscription_Readers: Still creating... [10s elapsed]
azurerm_role_assignment.L2_Subscription_Owners: Still creating... [20s elapsed]
azurerm_role_assignment.L2_Subscription_Readers: Still creating... [20s elapsed]
azurerm_role_assignment.L1_Subscription_Readers: Still creating... [20s elapsed]
azurerm_role_assignment.L1_Subscription_Readers: Creation complete after 23s [id=/subscriptions/c00dd93b-0f2b-4cd6-8273-e1038dcbd60e/providers/Microsoft.Authorization/roleAssignments/9b2a8cb5-7998-24ce-0169-03c1128930ea]
azurerm_role_assignment.L2_Subscription_Owners: Creation complete after 23s [id=/subscriptions/c00dd93b-0f2b-4cd6-8273-e1038dcbd60e/providers/Microsoft.Authorization/roleAssignments/cb1f86ed-8056-ef25-f73e-4971313ad945]
azurerm_role_assignment.L2_Subscription_Readers: Creation complete after 23s [id=/subscriptions/c00dd93b-0f2b-4cd6-8273-e1038dcbd60e/providers/Microsoft.Authorization/roleAssignments/87baa5aa-2da3-c687-db09-0b7067926bc5]

**Comment by bmaltais** [comment]
Odd... almost like Azure had not catched up with the code. Let me try it in the other subscription.

**Comment by bmaltais** [comment]
I have seen this yesterday also. I think it is an issue with Azure graph API not finding the resource even if it exist... just got the same I think:

```
Terraform returned errors:

Error: Error adding group member "aea74c39-1a88-47f5-8c31-a6d0c1173aa3" to Azure AD Group with ID "b965f54e-dbdb-4270-b1b8-9f05830525c7": graphrbac.GroupsClient#AddMember: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Authorization_RequestDenied","date":"2020-06-22T18:33:16","message":{"lang":"en","value":"Insufficient privileges to complete the operation."},"requestId":"fd9912d1-c150-4367-9f84-4328225a1dff"}}]

  on 5-L2_blueprint_project_members.tf line 9, in resource "azuread_group_member" "L2_Subscription_Contributors-Members":
   9: resource "azuread_group_member" "L2_Subscription_Contributors-Members" {



Error: Error adding group member "446fe20e-1b5c-45fc-a04e-5ae7cfb66684" to Azure AD Group with ID "b965f54e-dbdb-4270-b1b8-9f05830525c7": graphrbac.GroupsClient#AddMember: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Authorization_RequestDenied","date":"2020-06-22T18:33:16","message":{"lang":"en","value":"Insufficient privileges to complete the operation."},"requestId":"3a73da33-955e-42fc-a119-48c5e179686a"}}]

  on 5-L2_blueprint_project_members.tf line 9, in resource "azuread_group_member" "L2_Subscription_Contributors-Members":
   9: resource "azuread_group_member" "L2_Subscription_Contributors-Members" {



Error: Error adding group member "9a129a7b-1d7d-41af-88a0-7de17481a142" to Azure AD Group with ID "b965f54e-dbdb-4270-b1b8-9f05830525c7": graphrbac.GroupsClient#AddMember: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Authorization_RequestDenied","date":"2020-06-22T18:33:16","message":{"lang":"en","value":"Insufficient privileges to complete the operation."},"requestId":"7e28e173-c28c-4ccf-bea4-ac2399f8df45"}}]

  on 5-L2_blueprint_project_members.tf line 9, in resource "azuread_group_member" "L2_Subscription_Contributors-Members":
   9: resource "azuread_group_member" "L2_Subscription_Contributors-Members" {



Error: Error adding group member "d4decfde-8300-4fa4-aa36-7c22bf22a868" to Azure AD Group with ID "b965f54e-dbdb-4270-b1b8-9f05830525c7": graphrbac.GroupsClient#AddMember: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Authorization_RequestDenied","date":"2020-06-22T18:33:16","message":{"lang":"en","value":"Insufficient privileges to complete the operation."},"requestId":"2d199379-7d4e-4baa-b323-664edae729f6"}}]

  on 5-L2_blueprint_project_members.tf line 9, in resource "azuread_group_member" "L2_Subscription_Contributors-Members":
   9: resource "azuread_group_member" "L2_Subscription_Contributors-Members" {



Error: Error adding group member "bb294f5d-fece-4d3a-a187-7f98cb64e478" to Azure AD Group with ID "b965f54e-dbdb-4270-b1b8-9f05830525c7": graphrbac.GroupsClient#AddMember: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Authorization_RequestDenied","date":"2020-06-22T18:33:16","message":{"lang":"en","value":"Insufficient privileges to complete the operation."},"requestId":"aee32643-6f36-4859-a1e2-d9345a9e49e1"}}]

  on 5-L2_blueprint_project_members.tf line 17, in resource "azuread_group_member" "SP_L2_Subscription_Contributors-Members":
  17: resource "azuread_group_member" "SP_L2_Subscription_Contributors-Members" {



Error: Error adding group member "2000c7f5-0f8d-4a45-a65d-d70dc3edcac3" to Azure AD Group with ID "b965f54e-dbdb-4270-b1b8-9f05830525c7": graphrbac.GroupsClient#AddMember: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Authorization_RequestDenied","date":"2020-06-22T18:33:16","message":{"lang":"en","value":"Insufficient privileges to complete the operation."},"requestId":"b0fc52b0-cb17-455e-8331-0e2e5d1accb6"}}]

  on 5-L2_blueprint_project_members.tf line 17, in resource "azuread_group_member" "SP_L2_Subscription_Contributors-Members":
  17: resource "azuread_group_member" "SP_L2_Subscription_Contributors-Members" {

```

**Comment by enricked** [comment]
I received an 404, you received an 403 access Denied!

**Comment by bmaltais** [comment]
Yeah... different problem. Let's keep tracking it. I think it is an Azure fluke...

**Comment by bernardmaltais** [comment]
Closing as this appear to be an Azure API issue.
